### ISSUE TITLE
Add table cloudflare_certificates

### ISSUE THREAD

**Issue by jmreicha** [turbot/steampipe-plugin-cloudflare#155]
It appears there are APIs for retrieving certificate information, it would be nice to be able to view that information easily with Steampipe

**Comment by misraved** [comment]
Thanks @ParthaI for adding the API links 👍!!

If anyone is interested in trying to add these tables, we always appreciate any contributions to the plugin! For more information on our coding and documentation standards, please have a look at [Table and Column Standards](https://steampipe.io/docs/develop/standards) and [Table Documentation Standards](https://steampipe.io/docs/develop/table-docs-standards). If you have any questions about the development process otherwise, please let us know!
